<a href="https://colab.research.google.com/github/mitsu666/DataScienceLecture/blob/master/DataScienceLecture3_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. Numpy基礎

##1.1. NUMPY配列オブジェクト

In [0]:
#numpyモジュールをインポートする
import numpy as np

###1.1.1. NDARRAYの生成

####リストで作成

In [0]:
#引数にリスト
arr = np.array([1,2,3,4,3.14,9.99])

In [3]:
print (arr)
#type調べる
print (type(arr))
#サイズを調べる(shapeというアトリビュートを参照する)
print (arr.shape)

[1.   2.   3.   4.   3.14 9.99]
<class 'numpy.ndarray'>
(6,)


In [4]:
#リストの中にリストを持つケース。ネスト構造の内側のシーケンス同士の要素数が一致する場合に、ndarrayの多次元配列が生成される。
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
#中身確認
print (arr2)
#同じようにshape確認
print (arr2.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [5]:
#何次元配列か？
print (arr2.ndim)
#次元の要素数それぞれ
print (arr2.shape)
#変数の型は？
print (arr2.dtype)

2
(2, 4)
int64


####ZEROで作成

In [6]:
#要素10個がすべて0の1次元配列作成
print (np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
#4×2 要素すべてが0である配列作成
print (np.zeros((4,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


####ONESで生成

In [8]:
#np.onesはすべての要素を１にする。
print (np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
#4×2要素すべて1
print (np.ones((4,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


####EMPTYで生成

In [10]:
#np.emptyは要素を初期化せず戻してくれる。
print (np.empty(2))

[2.5468499e-316 9.8813129e-324]


In [11]:
#3次元配列
print (np.empty((2,3,2)))

[[[3.86800911e-316 0.00000000e+000]
  [4.11556683e-321 2.66943076e-316]
  [6.89934492e-310 6.89934492e-310]]

 [[6.89934492e-310 6.89934492e-310]
  [0.00000000e+000 1.97626258e-323]
  [1.90979621e-313 0.00000000e+000]]]


####ARANGEで生成

In [12]:
#arange
print (np.arange(15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [13]:
#rangeオブジェクトから生成
print (np.array(range(15)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [14]:
#同じかどうか
print (np.arange(15)==np.array(range(15)))

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True]


In [15]:
#2次元配列を作成
print (np.arange(15).reshape(5,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


####NDARRAY生成方法まとめ

In [16]:
#リストから作成
print (np.array([0,1,2]))
#タプルから作成
print (np.array((3,4,4,)))

[0 1 2]
[3 4 4]


In [17]:
#arangeで作成
print (np.arange(15))
#arangeで2次元配列作成
print (np.arange(15).reshape(3,5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [18]:
#ones
print (np.ones((3,4)))
#ones_like np配列を引数として受け取り同じ形ですべて1にする
print (np.ones_like(np.arange(15).reshape(3,5)))

#zeros
print (np.zeros((3,4)))
#ones_like np配列を引数として受け取り同じ形ですべて1にする
print (np.zeros_like(np.arange(15).reshape(3,5)))

#empty
print (np.empty((10,2)))
#ones_like np配列を引数として受け取り同じ形ですべて1にする
print (np.empty_like(np.arange(20).reshape(10,2)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[2.92881324e-316 5.38531554e-322]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.16095484e-028]
 [3.68423986e+180 5.56218858e+180]
 [1.54722523e+262 7.48952651e+247]
 [8.76739466e+252 8.89489936e+252]
 [1.17149199e+214 1.14428494e+243]
 [1.35617218e+248 2.78225511e+296]
 [7.67127212e+151 2.77620488e+184]
 [3.67150196e+228 1.48121964e+295]]
[[           59279840                 109]
 [                  0                   0]
 [                  0 4189022085447885435]
 [7308332238530945570 7310875413622977646]
 [8529661999317328428 8315171456806384225]
 [8391088104661531170 8391166427719365231]
 [7809635628709671535 8243121639893263731]
 [8319104478871053663 9041884596516319081]
 [6879089467297178156 7366237998127805555]
 [8026363953081969761 9022734504215998069]]


In [19]:
#単位行列の生成
print (np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


###1.1.2. NDARRAYのデータ型

In [0]:
#dtypeを明示する
arr1 = np.array([1,3,5],dtype=np.float64)

#dtypeを明示する
arr2 = np.array([1,3,5],dtype=np.int64)

In [21]:
print (arr1.dtype)
print (arr2.dtype)

float64
int64


In [22]:
#dtype = 整数
arr=np.array([1,2,3,4,5])
print (arr.dtype)

int64


In [23]:
#float型に変換
float_arr=arr.astype(np.float64)
print (float_arr.dtype)

float64


In [24]:
#小数型を整数型に変換する場合、小数部は次のように切り捨てられる。
arr=np.array([3.7,-1.2,-2.6,-.5,12.9,10.1])
print (arr)
#整数型に変換
print (arr.astype(np.int32))

[ 3.7 -1.2 -2.6 -0.5 12.9 10.1]
[ 3 -1 -2  0 12 10]


In [25]:
#数値が文字列として格納されている場合は、astypeを用いる。
#浮動小数点を表す文字列を格納する
numeric_strings = np.array(['3.14','1.732','1.414'],dtype=np.string_)
#確認
print (numeric_strings)

[b'3.14' b'1.732' b'1.414']


In [26]:
#文字列to数値変換
print (numeric_strings.astype(np.float))

[3.14  1.732 1.414]


In [0]:
#型名以外にも、型コードを指定することもできる。
empty_unit32=np.empty(8,dtype='u4')

In [28]:
print (empty_unit32)

[1 0 1 0 1 0 0 0]


###1.1.3. NDARRAYの算術演算

####加減乗除

In [29]:
#簡単なnumpy配列を作成
arr = np.array([[0,4,4],[3,1,1]])
print (arr)

[[0 4 4]
 [3 1 1]]


In [30]:
#加算1 ある定数との加法
print (arr+4)
#加算2 arr同志の加法
print (arr+arr)
#減法1 加法と同じ
print (arr-4)
#減法2 
print (arr-arr)
#乗法1
print (arr*3)

[[4 8 8]
 [7 5 5]]
[[0 8 8]
 [6 2 2]]
[[-4  0  0]
 [-1 -3 -3]]
[[0 0 0]
 [0 0 0]]
[[ 0 12 12]
 [ 9  3  3]]


In [31]:
#乗法2 
print (arr*arr)
#除法1
print (arr/4)
#除法2
print (arr/arr)

[[ 0 16 16]
 [ 9  1  1]]
[[0.   1.   1.  ]
 [0.75 0.25 0.25]]
[[nan  1.  1.]
 [ 1.  1.  1.]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """


####真偽判定

In [32]:
#ndaray間を比較したときに、その結果は同様素数の真偽値配列として戻される。
#適用なnumpy配列作成
arr2=np.array([[21.,19.,32.],[23.,44.,6.]])

print (arr2)

#20以上か
arr2>=20

[[21. 19. 32.]
 [23. 44.  6.]]


array([[ True, False,  True],
       [ True,  True, False]])

###1.1.4. インデックス参照とスライシングの基礎

In [33]:
#表面上Pythonのリストと同じような振る舞いをする。
arr=np.arange(10)
print (arr)
#3番地を指定
print (arr[3])

[0 1 2 3 4 5 6 7 8 9]
3


In [34]:
#3番地に100を代入
arr[3]=100
print (arr)

[  0   1   2 100   4   5   6   7   8   9]


In [35]:
#2次元配列
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

#3行3列配列確認
print (arr2d)

#一番上の行のみ取得
print ('一番上',arr2d[0])
#真ん中の行のみ取得
print ('真ん中',arr2d[1])
#一番下の行のみ取得
print ('一番下',arr2d[2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
一番上 [1 2 3]
真ん中 [4 5 6]
一番下 [7 8 9]


In [36]:
#1番上の行の真ん中の列にアクセスするには段階的な指定をする
#0番目の1番目
print (arr2d[0][1])

#もう少し簡単にすると、インデックスのコンマ区切りリストを使うことができる。
print (arr2d[0,2])

2
3


####スライス参照

In [37]:
l = [0,1,2,3,4,5]
#1番地から
print (l[1:])
#3番地まで
print (l[:3])

[1, 2, 3, 4, 5]
[0, 1, 2]


In [38]:
#1次元配列作成
arr = [31,14,56,7,8,2,0]
print (arr)

#リストと同じ :　でスライス参照
arr[1:6]

[31, 14, 56, 7, 8, 2, 0]


[14, 56, 7, 8, 2]

In [39]:
#arr2dを用いて２次元配列のスライシングをする。
arr2d = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

print (arr2d)

#「arr2dの最初の2行を切り出す」と理解するとわかりやすい。
print (arr2d[:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]


In [40]:
#①最初から2行目までかつ最初から1列目まで
print ('①',arr2d[:2,:1])
#②最初から2行目までかつ1列目から最後まで
print ('②',arr2d[:2,1:])
#③2行目から最後までかつ1列目から最後まで
print ('③',arr2d[2:,1:])

① [[1]
 [4]]
② [[2 3]
 [5 6]]
③ [[8 9]]


In [41]:
#2行面（1番地）かつ最初から2列目まで
print (arr2d[1, :2])

[4 5]


In [42]:
#すべての行かつ最初から1列目まで
print (arr2d[:,:1])

[[1]
 [4]
 [7]]


In [43]:
#スライス表記へのスカラー値の代入は、その範囲の要素すべてに対する代入を意味する。
arr2d[:2,1:] = 0
print (arr2d)

[[1 0 0]
 [4 0 0]
 [7 8 9]]


In [44]:
#arr_sliceというnumpyオブジェクトにarrの3番地から7番地を代入
arr_slice=arr[3:7]
print (arr_slice)

#arr_sliceの先頭に9999を代入する
arr_slice[0]=9999

#元のarrに代入されている
print (arr)

[7, 8, 2, 0]
[31, 14, 56, 7, 8, 2, 0]


####より高度な参照*

In [48]:
#3次元配列作成
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print (arr3d)
print (arr3d[0])

#arr3d[0]に値を代入することができる。スカラー値、ndarrayのどちらも指定可能である。
old_values=arr3d[0].copy()
arr3d[0]=100
print (arr3d)

#元に戻す
arr3d[0]=old_values
print (arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]
[[[100 100 100]
  [100 100 100]]

 [[  7   8   9]
  [ 10  11  12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


###1.1.5. ブールインデックス参照

In [49]:
#アジア諸国
countries = np.array(['日本' ,'インド' ,'インドネシア','韓国', 'サウジアラビア','シンガポール', 'タイ',
'中国','トルコ', 'パキスタン','バングラデシュ', 'フィリピン','香港', 'マレーシア'])

print (countries)

#GDP/一人当たりGDP (100万ドル)
data = np.array([[4892255,38313],
                [1281330,1085],
                [510504,2246],
                [931405,19343],
                [475094	,18853],
                 [188261	,40793],
                  [272429	,4043],
                  [4416104,	3360],
                  [730325	,9881],
                  [146068	,825],
                  [79568	,497],
                  [167479	,1854],
                  [215354	,30843],
                  [221437	,8197]])
print (data)
print (data.shape)

['日本' 'インド' 'インドネシア' '韓国' 'サウジアラビア' 'シンガポール' 'タイ' '中国' 'トルコ' 'パキスタン'
 'バングラデシュ' 'フィリピン' '香港' 'マレーシア']
[[4892255   38313]
 [1281330    1085]
 [ 510504    2246]
 [ 931405   19343]
 [ 475094   18853]
 [ 188261   40793]
 [ 272429    4043]
 [4416104    3360]
 [ 730325    9881]
 [ 146068     825]
 [  79568     497]
 [ 167479    1854]
 [ 215354   30843]
 [ 221437    8197]]
(14, 2)


In [50]:
#'data'から'日本'に対応する行を全て抜き出すことを考える。
print (countries=='日本')

[ True False False False False False False False False False False False
 False False]


In [51]:
#Trueのところだけ抜き出す
data[countries=='日本']
#約4.8兆ドル=500兆円(アベノミクスでは600兆円をめざしているらしいが))

array([[4892255,   38313]])

In [52]:
#列のスライスやインデックスも同時に指定することができる。
#1行目(0番地目)から
print (data[countries =='日本',0:])
#2行目(1番地目)のみ（ひとりあたりGDP)
print (data[countries=='日本',1])

[[4892255   38313]]
[38313]


In [53]:
#not日本か？
print (countries != '日本')

#日本以外
print (data[~(countries == '日本')])

[False  True  True  True  True  True  True  True  True  True  True  True
  True  True]
[[1281330    1085]
 [ 510504    2246]
 [ 931405   19343]
 [ 475094   18853]
 [ 188261   40793]
 [ 272429    4043]
 [4416104    3360]
 [ 730325    9881]
 [ 146068     825]
 [  79568     497]
 [ 167479    1854]
 [ 215354   30843]
 [ 221437    8197]]


In [54]:
#日本 or シンガポール
mask=(countries == '日本') | (countries == 'シンガポール')
print (mask)

#日本とシンガポールのGDP/一人あたりGDP
print (data[mask])
#一人あたり2009年時点で抜かれている

[ True False False False False  True False False False False False False
 False False]
[[4892255   38313]
 [ 188261   40793]]


In [55]:
#１兆ドル超えの国を0にしてみる
data[data>1000000]=0
print (data)

#特定の行や列に対する操作も、１次元の真偽値配列を使うことができる。
data[countries != '日本'] = 0
print (data)

[[     0  38313]
 [     0   1085]
 [510504   2246]
 [931405  19343]
 [475094  18853]
 [188261  40793]
 [272429   4043]
 [     0   3360]
 [730325   9881]
 [146068    825]
 [ 79568    497]
 [167479   1854]
 [215354  30843]
 [221437   8197]]
[[    0 38313]
 [    0     0]
 [    0     0]
 [    0     0]
 [    0     0]
 [    0     0]
 [    0     0]
 [    0     0]
 [    0     0]
 [    0     0]
 [    0     0]
 [    0     0]
 [    0     0]
 [    0     0]]


####実務ではこう使う

In [0]:
#年齢配列と名前配列を定義
age = np.array([[20,21,18,34]])
name = np.array([['A','B','C','D']])

In [57]:
#成人しているのは？
print (name[age>=20])
#未成年は？
print (name[~(age>=20)])
#Cの年齢20にする
age[name=='C'] = 20 
print (age)

['A' 'B' 'D']
['C']
[[20 21 20 34]]


###1.1.6. 行と列の入れ替え*

In [58]:
arr = np.arange(40).reshape(8,5)
#8行4列の配列
print (arr)

#行列ひっくりかえすにはTメソッドを使う(transposeのT)
arr.T

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


array([[ 0,  5, 10, 15, 20, 25, 30, 35],
       [ 1,  6, 11, 16, 21, 26, 31, 36],
       [ 2,  7, 12, 17, 22, 27, 32, 37],
       [ 3,  8, 13, 18, 23, 28, 33, 38],
       [ 4,  9, 14, 19, 24, 29, 34, 39]])

In [59]:
#行列の計算 自分自身と自分をかけている
print (np.dot(arr.T,arr))

[[3500 3640 3780 3920 4060]
 [3640 3788 3936 4084 4232]
 [3780 3936 4092 4248 4404]
 [3920 4084 4248 4412 4576]
 [4060 4232 4404 4576 4748]]


##1.2. ユニバーサル関数

###1.2.1. 1次元配列の場合

In [60]:
#ルートを計算
arr=np.arange(5)
print (arr)

#npのsqrtメソッドを使用
print (np.sqrt(arr))
#ルート2は「ひとよひとよに」
print (np.sqrt(arr)[2])

[0 1 2 3 4]
[0.         1.         1.41421356 1.73205081 2.        ]
1.4142135623730951


In [61]:
#指数関数(exponential)
print (np.exp(arr))
#対数関数(log) +1 はlog(0)を避けるため
print (np.log(arr+1))
#max関数
print (np.max(arr))
#min関数
print (np.min(arr))

[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
4
0


###1.2.2. 2次元配列の場合

In [62]:
#2次元配列生成
arr2 = np.arange(20).reshape(5,4)
print (arr2)
#指数関数(exponential)
print (np.exp(arr2))
#対数関数(log) +1 はlog(0)を避けるため
print (np.log(arr2+1))
#max関数
print (np.max(arr2))
#min関数
print (np.min(arr2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]
 [1.62754791e+05 4.42413392e+05 1.20260428e+06 3.26901737e+06]
 [8.88611052e+06 2.41549528e+07 6.56599691e+07 1.78482301e+08]]
[[0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.79175947 1.94591015 2.07944154]
 [2.19722458 2.30258509 2.39789527 2.48490665]
 [2.56494936 2.63905733 2.7080502  2.77258872]
 [2.83321334 2.89037176 2.94443898 2.99573227]]
19
0


###1.2.3. 引数2つの場合*

In [63]:
#乱数で1次元配列2つ作成
np.random.seed(100) #乱数が固定するおまじない
x = np.random.rand(10)
y = np.random.rand(10)

print (x)
print (y)

#xとyの大きい方を取得
np.maximum(x,y)

[0.54340494 0.27836939 0.42451759 0.84477613 0.00471886 0.12156912
 0.67074908 0.82585276 0.13670659 0.57509333]
[0.89132195 0.20920212 0.18532822 0.10837689 0.21969749 0.97862378
 0.81168315 0.17194101 0.81622475 0.27407375]


array([0.89132195, 0.27836939, 0.42451759, 0.84477613, 0.21969749,
       0.97862378, 0.81168315, 0.82585276, 0.81622475, 0.57509333])

##1.3. 配列指向プログラミング

###1.3.1. 条件制御のNDARRAYでの表現

In [64]:
#年齢/性別変
age = np.array([21,33,17,24])

#np.where #飲酒OK?
print (np.where(age>=20,'OK','NO'))

['OK' 'OK' 'NO' 'OK']


In [65]:
#実は20歳でした 20歳以上の人はそのまま それ以外は20歳にする
np.where(age>=20,age,20)

array([21, 33, 20, 24])

In [66]:
#さっきのbool参照で似たようなことできる
age[age<20] = 20 
print (age)

[21 33 20 24]


In [68]:
#購買金額が0未満は0に直す
amount = np.array([9900,3400,-900])
print (amount)
print (np.where(amount<0,0,amount))

[9900 3400 -900]
[9900 3400    0]


###1.3.2. 数学関数、統計関数

In [69]:
#配列作成
arr=np.arange(5)
print (arr)

[0 1 2 3 4]


In [70]:
#さっきやったやり方で平均
print (np.mean(arr))
#さっきやったやり方で最大
print (np.max(arr))
#さっきやったやり方で最小
print (np.min(arr))
#さっきやったやり方で全部足す
print (np.sum(arr))

2.0
4
0
10


In [71]:
#配列オブジェクトのもつメソッドで行う平均
print (arr.mean())
#最大
print (arr.max())
#最小
print (arr.min())
#全部足す
print (arr.sum())

2.0
4
0
10


In [72]:
#2次元配列の場合、行か列どちらかを指定してその方向に平均・最大・最小・全部の加法を行う。
#GDP/一人当たりGDP (100万ドル)
data = np.array([[4892255,38313],
                [1281330,1085],
                [510504,2246],
                [931405,19343],
                [475094	,18853],
                 [188261	,40793],
                  [272429	,4043],
                  [4416104,	3360],
                  [730325	,9881],
                  [146068	,825],
                  [79568	,497],
                  [167479	,1854],
                  [215354	,30843],
                  [221437	,8197]])
print (data)
print (data.shape)

[[4892255   38313]
 [1281330    1085]
 [ 510504    2246]
 [ 931405   19343]
 [ 475094   18853]
 [ 188261   40793]
 [ 272429    4043]
 [4416104    3360]
 [ 730325    9881]
 [ 146068     825]
 [  79568     497]
 [ 167479    1854]
 [ 215354   30843]
 [ 221437    8197]]
(14, 2)


In [73]:
#行（縦)方向に平均アジアの国のGDP平均と一人あたりGDPの平均 axis=0 で縦方向
print (data.mean(axis=0))
#列（横方向に平均）国のGDPと一人あたりGDPの平均（例ではあるが実際にこの数値に意味はない axis=1 で縦方向
print (data.mean(axis=1))

[1037686.64285714   12866.64285714]
[2465284.   641207.5  256375.   475374.   246973.5  114527.   138236.
 2209732.   370103.    73446.5   40032.5   84666.5  123098.5  114817. ]


In [74]:
#同様にアジアの国GDPの総和
data.sum(axis=0)

array([14527613,   180133])

###1.3.3. 真偽配列関数*

In [75]:
#乱数作成
arr=np.random.randn(100)

#正の数の個数
(arr>0).sum()

47

In [77]:
#bool配列作成
bools=np.array([False,False,True,False])
#anyは要素の１つでもTrueがあるかどうかを確認するときに用いられる。
print (bools.any())
#allは要素のすべてがTrueであるかどうかを確認するときに用いられる。
print (bools.all())

True
False
